"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getInventoryBalances, getInventoryWarehouses, scrapInventory, transferInventory } from "@/lib/inventoryApi";
import type { InventoryBalance, InventoryWarehouse } from "@/lib/inventoryTypes";

export default function InventoryTransferWorkbench({ notify }: { notify: (message: string, error?: boolean) => void }) {
  const [balances, setBalances] = useState<InventoryBalance[]>([]); const [warehouses, setWarehouses] = useState<InventoryWarehouse[]>([]); const [selectedKey, setSelectedKey] = useState(""); const [mode, setMode] = useState<"transfer" | "scrap">("transfer"); const [targetWarehouse, setTargetWarehouse] = useState(""); const [targetLocation, setTargetLocation] = useState(""); const [quantity, setQuantity] = useState(0); const [productionNo, setProductionNo] = useState(""); const [remark, setRemark] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [nextBalances, nextWarehouses] = await Promise.all([getInventoryBalances(), getInventoryWarehouses()]); setBalances(nextBalances.filter((item) => item.available > 0)); setWarehouses(nextWarehouses); } catch (error) { notify(msg(error, "库存作业数据加载失败"), true); } }, [notify]);
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, [load]);
  const balance = useMemo(() => balances.find((item) => key(item) === selectedKey), [balances, selectedKey]); const target = warehouses.find((item) => item.id === Number(targetWarehouse));
  const submit = async () => { if (!balance || quantity <= 0) return notify("请选择库存并填写数量", true); setBusy(true); try { const result = mode === "transfer" ? await transferInventory({ remark, items: [{ material_id: balance.material_id, source_warehouse_id: balance.warehouse_id, source_location_id: balance.location_id, target_warehouse_id: Number(targetWarehouse), target_location_id: Number(targetLocation), quantity, unit: balance.unit, remark }] }) : await scrapInventory({ production_no: productionNo, remark, items: [{ material_id: balance.material_id, warehouse_id: balance.warehouse_id, location_id: balance.location_id, quantity, unit: balance.unit, remark }] }); notify(result.message); setQuantity(0); setRemark(""); await load(); } catch (error) { notify(msg(error, mode === "transfer" ? "库存调拨失败" : "报废出库失败"), true); } finally { setBusy(false); } };
  return <section className="border border-[#D1D1D6] bg-white"><header className="flex items-center gap-2 border-b border-[#E5E5EA] p-4"><div className="mr-auto"><h2 className="font-semibold">调拨与报废</h2><p className="mt-1 text-xs text-[#636366]">只允许操作可用库存，已被生产单占用的数量不会被挪用。</p></div><button onClick={() => setMode("transfer")} className={`h-8 px-3 text-xs ${mode === "transfer" ? "bg-[#007AFF] text-white" : "border border-[#C7C7CC]"}`}>库存调拨</button><button onClick={() => setMode("scrap")} className={`h-8 px-3 text-xs ${mode === "scrap" ? "bg-[#C62828] text-white" : "border border-[#C7C7CC]"}`}>报废出库</button></header><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4"><Field label="调出库存"><select value={selectedKey} onChange={(event) => setSelectedKey(event.target.value)} className="control"><option value="">请选择物料与库位</option>{balances.map((item) => <option key={key(item)} value={key(item)}>{item.material_code} · {item.material_name} · {item.warehouse_name}/{item.location_name} · 可用 {item.available}</option>)}</select></Field>{mode === "transfer" ? <><Field label="调入仓库"><select value={targetWarehouse} onChange={(event) => { setTargetWarehouse(event.target.value); setTargetLocation(warehouses.find((item) => item.id === Number(event.target.value))?.locations[0]?.id.toString() || ""); }} className="control"><option value="">请选择仓库</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="调入库位"><select value={targetLocation} onChange={(event) => setTargetLocation(event.target.value)} className="control"><option value="">请选择库位</option>{target?.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></> : <Field label="关联生产编号"><input value={productionNo} onChange={(event) => setProductionNo(event.target.value)} className="control" placeholder="可选" /></Field>}<Field label={`数量${balance ? `（最多 ${balance.available} ${balance.unit}）` : ""}`}><input type="number" min="0" max={balance?.available} value={quantity || ""} onChange={(event) => setQuantity(Number(event.target.value) || 0)} className="control" /></Field><Field label="原因/备注"><input value={remark} onChange={(event) => setRemark(event.target.value)} className="control" placeholder={mode === "transfer" ? "移库原因" : "报废原因"} /></Field><div className="flex items-end"><button disabled={busy || !balance || quantity <= 0 || (mode === "transfer" && (!targetWarehouse || !targetLocation))} onClick={() => void submit()} className={`h-10 w-full text-sm text-white disabled:bg-[#C7C7CC] ${mode === "transfer" ? "bg-[#007AFF]" : "bg-[#C62828]"}`}>确认{mode === "transfer" ? "调拨" : "报废"}</button></div></div><style jsx>{`.control{height:2.5rem;width:100%;border:1px solid #c7c7cc;padding:0 .75rem;font-size:.875rem;background:#fff}`}</style></section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs text-[#636366]">{label}<div className="mt-1">{children}</div></label>; }
function key(item: InventoryBalance) { return `${item.material_id}-${item.warehouse_id}-${item.location_id}`; }
function msg(error: unknown, fallback: string) { return (error as { userMessage?: string; message?: string })?.userMessage || (error as { message?: string })?.message || fallback; }
