"use client";

import { useEffect, useState } from "react";
import { getInventoryWarehouses, getPurchaseReceipt, getPurchaseReceipts, inspectPurchaseReceiptItem } from "@/lib/inventoryApi";
import type { InventoryWarehouse, PurchaseReceipt, PurchaseReceiptItem } from "@/lib/inventoryTypes";

export default function ReceivingWorkbench({notify}:{notify:(message:string,error?:boolean)=>void}){
  const [receipts,setReceipts]=useState<PurchaseReceipt[]>([]); const [warehouses,setWarehouses]=useState<InventoryWarehouse[]>([]); const [selected,setSelected]=useState<PurchaseReceipt|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{void (async()=>{try{setReceipts(await getPurchaseReceipts("待检"));setWarehouses(await getInventoryWarehouses())}catch(error){notify(msg(error,"待检物料加载失败"),true)}})()},[notify]);
  const choose=async(id:number)=>{setBusy(true);try{setSelected(await getPurchaseReceipt(id))}catch(error){notify(msg(error,"到货单加载失败"),true)}finally{setBusy(false)}};
  const inspect=async(item:PurchaseReceiptItem,form:InspectionForm)=>{setBusy(true);try{const result=await inspectPurchaseReceiptItem(item.id,{qualified_quantity:form.qualified,concession_quantity:form.concession,rejected_quantity:form.rejected,warehouse_id:form.warehouseId,location_id:form.locationId,remark:form.remark});notify(result.message);setSelected(result.receipt.status==="待检"?result.receipt:null);const rows=await getPurchaseReceipts("待检");setReceipts(rows)}catch(error){notify(msg(error,"来料检验失败"),true)}finally{setBusy(false)}};
  return <div className="grid gap-4 xl:grid-cols-[360px_minmax(0,1fr)]"><aside className="border border-[#D1D1D6] bg-white"><header className="border-b border-[#E5E5EA] p-4"><h2 className="font-semibold">到货待检</h2><p className="mt-1 text-xs text-[#636366]">到货只登记数量，检验接收后才进入库存。</p></header>{receipts.map(r=><button key={r.id} onClick={()=>void choose(r.id)} className={`block w-full border-b border-[#E5E5EA] p-4 text-left ${selected?.id===r.id?"bg-[#EDF6FF]":"bg-white"}`}><div className="flex justify-between"><strong className="text-sm">{r.receipt_no}</strong><span className="text-xs text-[#C76E00]">{r.status}</span></div><div className="mt-1 text-sm">{r.supplier}</div><div className="mt-2 text-xs text-[#636366]">{r.order_no} · {r.item_count} 项 · {r.arrival_date}</div></button>)}{!receipts.length&&<div className="p-8 text-center text-sm text-[#8E8E93]">没有待检到货单</div>}</aside><section className="min-h-96 border border-[#D1D1D6] bg-white">{!selected?<div className="flex min-h-96 items-center justify-center text-sm text-[#8E8E93]">选择左侧到货单进行来料检验</div>:<><header className="border-b border-[#E5E5EA] p-4"><h2 className="font-semibold">{selected.receipt_no} · {selected.supplier}</h2><p className="mt-1 text-xs text-[#636366]">采购单 {selected.order_no} · 到货日期 {selected.arrival_date}</p></header><div className="space-y-3 p-4">{(selected.items||[]).map(item=><InspectionRow key={item.id} item={item} warehouses={warehouses} busy={busy} onSubmit={(form)=>inspect(item,form)}/>)}</div></>}</section></div>
}
type InspectionForm={qualified:number;concession:number;rejected:number;warehouseId:number;locationId:number;remark:string};
function InspectionRow({item,warehouses,busy,onSubmit}:{item:PurchaseReceiptItem;warehouses:InventoryWarehouse[];busy:boolean;onSubmit:(form:InspectionForm)=>Promise<void>}){const defaultWarehouse=warehouses.find(w=>w.locations.length)||warehouses[0];const [form,setForm]=useState<InspectionForm>({qualified:item.received_quantity,concession:0,rejected:0,warehouseId:defaultWarehouse?.id||0,locationId:defaultWarehouse?.locations[0]?.id||0,remark:""});const warehouse=warehouses.find(w=>w.id===form.warehouseId);return <div className="border border-[#D1D1D6] p-3"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><strong className="text-sm">{item.material_name}</strong><span className="ml-2 text-xs text-[#636366]">{item.material_code} · {item.specification||"-"} · 到货 {item.received_quantity} {item.unit}</span></div><span className="text-xs text-[#C76E00]">{item.status}</span></div><div className="mt-3 grid gap-2 md:grid-cols-3 xl:grid-cols-7"><NumberInput label="合格" value={form.qualified} onChange={v=>setForm({...form,qualified:v})}/><NumberInput label="让步接收" value={form.concession} onChange={v=>setForm({...form,concession:v})}/><NumberInput label="不合格" value={form.rejected} onChange={v=>setForm({...form,rejected:v})}/><label className="text-xs text-[#636366]">仓库<select value={form.warehouseId} onChange={e=>{const id=Number(e.target.value);const next=warehouses.find(w=>w.id===id);setForm({...form,warehouseId:id,locationId:next?.locations[0]?.id||0})}} className="mt-1 h-9 w-full border border-[#C7C7CC] px-2 text-sm text-[#1C1C1E]">{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-xs text-[#636366]">库位<select value={form.locationId} onChange={e=>setForm({...form,locationId:Number(e.target.value)})} className="mt-1 h-9 w-full border border-[#C7C7CC] px-2 text-sm text-[#1C1C1E]">{(warehouse?.locations||[]).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="text-xs text-[#636366]">备注<input value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})} className="mt-1 h-9 w-full border border-[#C7C7CC] px-2 text-sm text-[#1C1C1E]"/></label><div className="flex items-end"><button disabled={busy||!form.warehouseId||!form.locationId} onClick={()=>void onSubmit(form)} className="h-9 w-full bg-[#248A3D] px-3 text-sm text-white disabled:bg-[#C7C7CC]">提交检验并入库</button></div></div></div>}
function NumberInput({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="text-xs text-[#636366]">{label}<input type="number" min="0" value={value} onChange={e=>onChange(Number(e.target.value)||0)} className="mt-1 h-9 w-full border border-[#C7C7CC] px-2 text-sm text-[#1C1C1E]"/></label>}
function msg(error:unknown,fallback:string){return (error as {userMessage?:string;message?:string})?.userMessage||(error as {message?:string})?.message||fallback}
