"use client";

import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getRouteTemplates, updateRouteTemplate } from "@/lib/operationsApi";
import type { RouteStep, RouteTemplate } from "@/lib/operationsTypes";

const blankStep = (index:number):RouteStep => ({step_code:`STEP_${index+1}`,name:"新工序",category:"加工",sequence_no:index+1,predecessor_codes:[],material_operations:[],inspection_required:false,standard_minutes:0,piece_rate:0,default_role:"",work_center:"",weight:10,is_active:true});

export default function RouteTemplateCatalog({notify}:{notify:(message:string,error?:boolean)=>void}){
  const [templates,setTemplates]=useState<RouteTemplate[]>([]); const [selected,setSelected]=useState(0); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const rows=await getRouteTemplates();setTemplates(rows);setSelected(value=>Math.min(value,Math.max(0,rows.length-1)));},[]);
  useEffect(()=>{void load().catch(error=>notify(msg(error,"工艺路线加载失败"),true));},[load,notify]);
  const template=templates[selected];
  const patchStep=(index:number,patch:Partial<RouteStep>)=>setTemplates(rows=>rows.map((item,i)=>i===selected?{...item,steps:item.steps.map((step,j)=>j===index?{...step,...patch}:step)}:item));
  const move=(index:number,delta:number)=>{const target=index+delta;if(!template||target<0||target>=template.steps.length)return;const steps=[...template.steps];[steps[index],steps[target]]=[steps[target],steps[index]];steps.forEach((step,i)=>step.sequence_no=i+1);setTemplates(rows=>rows.map((item,i)=>i===selected?{...item,steps}:item));};
  const save=async()=>{if(!template)return;setBusy(true);try{const result=await updateRouteTemplate(template);notify(result.message);await load();}catch(error){notify(msg(error,"工艺路线保存失败"),true);}finally{setBusy(false);}};
  if(!template)return <div className="workspace-panel p-10 text-center text-sm text-[#8E8E93]">暂无工艺路线模板</div>;
  return <section className="workspace-panel overflow-hidden"><header className="workspace-panel__header"><div><h2>标准工艺路线</h2><p>新生成的门樘采用当前模板；已发布门樘保留原路线快照，不随模板变化。</p></div><div className="flex gap-2"><select value={selected} onChange={e=>setSelected(Number(e.target.value))} className="h-9 border border-[#C7C7CC] bg-white px-3 text-sm">{templates.map((item,index)=><option key={item.id} value={index}>{item.name} · V{item.version}</option>)}</select><button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void save()}><Save size={15}/>保存模板</button></div></header>
    <div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-sm"><thead><tr>{["顺序","工序编码","工序名称","类别","前序工序","工作中心","标准分钟","计件单价","质检","操作"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{template.steps.map((step,index)=><tr key={`${step.step_code}-${index}`}><td>{index+1}</td><td><input value={step.step_code} onChange={e=>patchStep(index,{step_code:e.target.value.toUpperCase()})}/></td><td><input value={step.name} onChange={e=>patchStep(index,{name:e.target.value})}/></td><td><input value={step.category} onChange={e=>patchStep(index,{category:e.target.value})}/></td><td><input value={step.predecessor_codes.join("、")} onChange={e=>patchStep(index,{predecessor_codes:e.target.value.split(/[、,，]/).map(v=>v.trim()).filter(Boolean)})}/></td><td><input value={step.work_center} onChange={e=>patchStep(index,{work_center:e.target.value})}/></td><td><input type="number" min="0" value={step.standard_minutes||""} onChange={e=>patchStep(index,{standard_minutes:Number(e.target.value)||0})}/></td><td><input type="number" min="0" value={step.piece_rate||""} onChange={e=>patchStep(index,{piece_rate:Number(e.target.value)||0})}/></td><td><input type="checkbox" checked={step.inspection_required} onChange={e=>patchStep(index,{inspection_required:e.target.checked})}/></td><td><div className="flex gap-1"><button title="上移" onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button title="下移" onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button title="删除" onClick={()=>setTemplates(rows=>rows.map((item,i)=>i===selected?{...item,steps:item.steps.filter((_,j)=>j!==index).map((s,j)=>({...s,sequence_no:j+1}))}:item))}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>
    <div className="p-4"><button className="ui-button ui-button--secondary" onClick={()=>setTemplates(rows=>rows.map((item,i)=>i===selected?{...item,steps:[...item.steps,blankStep(item.steps.length)]}:item))}><Plus size={15}/>新增工序</button></div>
    <style jsx>{`th,td{border-bottom:1px solid #e5e5ea;padding:.65rem;text-align:left}th{background:#f7f7f9;color:#636366;font-size:.75rem;font-weight:500}td input:not([type=checkbox]){height:2.25rem;width:100%;min-width:90px;border:1px solid #c7c7cc;padding:0 .5rem;background:#fff}td:nth-child(5) input{min-width:150px}td button{display:inline-grid;height:2rem;width:2rem;place-items:center;border:1px solid #d1d1d6;background:#fff}`}</style>
  </section>;
}
function msg(error:unknown,fallback:string){return (error as {userMessage?:string;message?:string})?.userMessage||(error as {message?:string})?.message||fallback}
