"use client";

import { useCallback, useEffect, useState } from "react";
import {
  createInventorySupplier, createInventorySupplierItem, getInventoryMaterials, getInventorySupplierItems,
  getInventorySuppliers, updateInventorySupplier, updateInventorySupplierItem,
} from "@/lib/inventoryApi";
import type { InventoryMaterial, InventorySupplier, InventorySupplierItem, SupplierItemPayload, SupplierPayload } from "@/lib/inventoryTypes";

const EMPTY_SUPPLIER: SupplierPayload = { code: "", name: "", short_name: "", contact_name: "", phone: "", address: "", invoice_title: "", tax_no: "", default_tax_rate: 0, settlement_method: "", payment_days: 0, default_lead_days: 0, supply_category: "", remark: "", is_active: true };

function emptyRelation(supplierId: number): SupplierItemPayload {
  return { supplier_id: supplierId, material_id: 0, supplier_item_code: "", supplier_item_name: "", purchase_specification: "", purchase_unit: "", conversion_rate: 1, tax_inclusive_price: 0, tax_rate: 0, minimum_order_quantity: 0, lead_days: 0, is_preferred: false, remark: "", is_active: true };
}

export default function SupplierCatalog({ notify }: { notify: (message: string, error?: boolean) => void }) {
  const [suppliers, setSuppliers] = useState<InventorySupplier[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [relations, setRelations] = useState<InventorySupplierItem[]>([]);
  const [materials, setMaterials] = useState<InventoryMaterial[]>([]);
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(true);
  const [supplierEditor, setSupplierEditor] = useState<InventorySupplier | "new" | null>(null);
  const [relationEditor, setRelationEditor] = useState<InventorySupplierItem | "new" | null>(null);

  const loadSuppliers = useCallback(async () => {
    setLoading(true);
    try {
      const rows = await getInventorySuppliers({ q: q || undefined, include_inactive: true });
      setSuppliers(rows);
      setSelectedId((current) => current && rows.some((item) => item.id === current) ? current : rows[0]?.id || null);
    } catch (error) { notify(apiMessage(error, "供应商加载失败"), true); }
    finally { setLoading(false); }
  }, [notify, q]);

  useEffect(() => { void loadSuppliers(); getInventoryMaterials().then(setMaterials).catch(() => undefined); }, [loadSuppliers]);
  useEffect(() => {
    if (!selectedId) { setRelations([]); return; }
    getInventorySupplierItems({ supplier_id: selectedId }).then(setRelations).catch((error) => notify(apiMessage(error, "供货商品加载失败"), true));
  }, [notify, selectedId]);

  const selected = suppliers.find((item) => item.id === selectedId) || null;
  const refreshRelations = async () => { if (selectedId) setRelations(await getInventorySupplierItems({ supplier_id: selectedId })); };

  return <section className="grid min-h-[620px] border border-[#D1D1D6] bg-white lg:grid-cols-[340px_minmax(0,1fr)]">
    <aside className="border-b border-[#D1D1D6] lg:border-b-0 lg:border-r">
      <div className="border-b border-[#E5E5EA] p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">供应商</h2><p className="mt-1 text-xs text-[#636366]">统一联系人、结算和交期资料</p></div><button onClick={() => setSupplierEditor("new")} className="h-8 bg-[#007AFF] px-3 text-xs text-white">新增</button></div><div className="mt-3 flex gap-2"><input value={q} onChange={(event) => setQ(event.target.value)} onKeyDown={(event) => event.key === "Enter" && void loadSuppliers()} placeholder="编码、名称、电话" className="h-9 min-w-0 flex-1 border border-[#C7C7CC] px-3 text-sm" /><button onClick={() => void loadSuppliers()} className="h-9 border border-[#C7C7CC] px-3 text-sm">查询</button></div></div>
      <div className="max-h-[650px] overflow-y-auto">{loading ? <Empty text="正在加载..." /> : suppliers.length ? suppliers.map((supplier) => <button key={supplier.id} onClick={() => setSelectedId(supplier.id)} className={`block w-full border-b border-[#E5E5EA] p-4 text-left ${selectedId === supplier.id ? "bg-[#EDF6FF]" : "hover:bg-[#F8F8FA]"}`}><div className="flex items-center justify-between gap-3"><strong className="truncate text-sm">{supplier.name}</strong><span className="text-xs text-[#636366]">{supplier.item_count} 项</span></div><div className="mt-1 flex justify-between text-xs text-[#636366]"><span>{supplier.code}</span><span>{supplier.contact_name || "未填联系人"} {supplier.phone}</span></div></button>) : <Empty text="暂无供应商" />}</div>
    </aside>
    <div className="min-w-0">{!selected ? <Empty text="选择供应商查看供货商品" tall /> : <><header className="flex flex-wrap items-start gap-3 border-b border-[#E5E5EA] p-5"><div className="flex-1"><div className="flex items-center gap-2"><h2 className="font-semibold">{selected.name}</h2><span className={`px-2 py-0.5 text-xs ${selected.is_active ? "bg-[#E7F7EA] text-[#248A3D]" : "bg-[#F2F2F7] text-[#8E8E93]"}`}>{selected.is_active ? "合作中" : "已停用"}</span></div><p className="mt-2 text-sm text-[#636366]">{selected.contact_name || "未填联系人"} · {selected.phone || "未填电话"} · 标准交期 {selected.default_lead_days || 0} 天 · 账期 {selected.payment_days || 0} 天</p><p className="mt-1 text-xs text-[#8E8E93]">{selected.address || "未填写地址"}</p></div><button onClick={() => setSupplierEditor(selected)} className="h-9 border border-[#C7C7CC] px-4 text-sm">编辑供应商</button><button onClick={() => setRelationEditor("new")} className="h-9 bg-[#007AFF] px-4 text-sm text-white">添加供货商品</button></header><div className="p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{relations.length ? relations.map((item) => <button key={item.id} onClick={() => setRelationEditor(item)} className="border border-[#D1D1D6] p-4 text-left hover:border-[#007AFF]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><strong className="block truncate text-sm">{item.material_name}</strong><span className="mt-1 block text-xs text-[#636366]">{item.material_code} · {item.purchase_specification || item.material_specification || "无规格"}</span></div>{item.is_preferred ? <span className="shrink-0 bg-[#EDF6FF] px-2 py-0.5 text-[11px] text-[#007AFF]">首选</span> : null}</div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div><span className="block text-[#8E8E93]">含税价</span><strong className="mt-1 block text-sm">¥{item.tax_inclusive_price}</strong></div><div><span className="block text-[#8E8E93]">交期</span><strong className="mt-1 block text-sm">{item.lead_days} 天</strong></div><div><span className="block text-[#8E8E93]">起订量</span><strong className="mt-1 block text-sm">{item.minimum_order_quantity || 0}</strong></div></div><p className="mt-3 truncate text-xs text-[#636366]">供应商货号：{item.supplier_item_code || "-"}</p></button>) : <div className="col-span-full border border-dashed border-[#C7C7CC] py-16 text-center text-sm text-[#8E8E93]">尚未维护该供应商的供货商品</div>}</div></div></>}</div>
    {supplierEditor && <SupplierDialog supplier={supplierEditor === "new" ? null : supplierEditor} onClose={() => setSupplierEditor(null)} onSaved={async (message) => { setSupplierEditor(null); notify(message); await loadSuppliers(); }} notify={notify} />}
    {relationEditor && selected && <RelationDialog relation={relationEditor === "new" ? null : relationEditor} supplier={selected} materials={materials} onClose={() => setRelationEditor(null)} onSaved={async (message) => { setRelationEditor(null); notify(message); await refreshRelations(); await loadSuppliers(); }} notify={notify} />}
  </section>;
}

function SupplierDialog({ supplier, onClose, onSaved, notify }: { supplier: InventorySupplier | null; onClose: () => void; onSaved: (message: string) => Promise<void>; notify: (message: string, error?: boolean) => void }) {
  const [form, setForm] = useState<SupplierPayload>(supplier ? { ...supplier, is_active: Boolean(supplier.is_active) } : EMPTY_SUPPLIER);
  const [busy, setBusy] = useState(false);
  const set = <K extends keyof SupplierPayload>(key: K, value: SupplierPayload[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { if (!form.code.trim() || !form.name.trim()) { notify("供应商编码和名称为必填项", true); return; } setBusy(true); try { const result = supplier ? await updateInventorySupplier(supplier.id, form) : await createInventorySupplier(form); await onSaved(result.message); } catch (error) { notify(apiMessage(error, "供应商保存失败"), true); } finally { setBusy(false); } };
  return <Dialog title={supplier ? "编辑供应商" : "新增供应商"} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Text label="供应商编码 *" value={form.code} onChange={(value) => set("code", value)} /><Text label="供应商名称 *" value={form.name} onChange={(value) => set("name", value)} /><Text label="简称" value={form.short_name} onChange={(value) => set("short_name", value)} /><Text label="联系人" value={form.contact_name} onChange={(value) => set("contact_name", value)} /><Text label="电话" value={form.phone} onChange={(value) => set("phone", value)} /><Text label="供应类别" value={form.supply_category} onChange={(value) => set("supply_category", value)} /><Text label="结算方式" value={form.settlement_method} onChange={(value) => set("settlement_method", value)} /><NumberField label="账期（天）" value={form.payment_days} onChange={(value) => set("payment_days", value)} /><NumberField label="标准交期（天）" value={form.default_lead_days} onChange={(value) => set("default_lead_days", value)} /><Text label="开票抬头" value={form.invoice_title} onChange={(value) => set("invoice_title", value)} /><Text label="税号" value={form.tax_no} onChange={(value) => set("tax_no", value)} /><NumberField label="默认税率（%）" value={form.default_tax_rate} onChange={(value) => set("default_tax_rate", value)} /><label className="text-xs text-[#636366] sm:col-span-2 lg:col-span-3">地址<input value={form.address} onChange={(event) => set("address", event.target.value)} className="mt-1 h-10 w-full border border-[#C7C7CC] px-3 text-sm text-[#1C1C1E]" /></label><label className="text-xs text-[#636366] sm:col-span-2 lg:col-span-3">备注<textarea value={form.remark} onChange={(event) => set("remark", event.target.value)} className="mt-1 min-h-20 w-full border border-[#C7C7CC] p-3 text-sm text-[#1C1C1E]" /></label>{supplier && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.is_active)} onChange={(event) => set("is_active", event.target.checked)} />启用</label>}</div><Actions busy={busy} onClose={onClose} onSubmit={submit} /></Dialog>;
}

function RelationDialog({ relation, supplier, materials, onClose, onSaved, notify }: { relation: InventorySupplierItem | null; supplier: InventorySupplier; materials: InventoryMaterial[]; onClose: () => void; onSaved: (message: string) => Promise<void>; notify: (message: string, error?: boolean) => void }) {
  const [form, setForm] = useState<SupplierItemPayload>(relation ? { ...relation, is_preferred: Boolean(relation.is_preferred), is_active: Boolean(relation.is_active) } : emptyRelation(supplier.id));
  const [busy, setBusy] = useState(false);
  const set = <K extends keyof SupplierItemPayload>(key: K, value: SupplierItemPayload[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { if (!form.material_id) { notify("请选择供货商品", true); return; } setBusy(true); try { const result = relation ? await updateInventorySupplierItem(relation.id, form) : await createInventorySupplierItem(form); await onSaved(result.message); } catch (error) { notify(apiMessage(error, "供货关系保存失败"), true); } finally { setBusy(false); } };
  return <Dialog title={`${supplier.name} · 供货商品`} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs text-[#636366] sm:col-span-2">物料与商品 *<select disabled={Boolean(relation)} value={form.material_id || ""} onChange={(event) => { const material = materials.find((item) => item.id === Number(event.target.value)); setForm((current) => ({ ...current, material_id: Number(event.target.value), supplier_item_name: current.supplier_item_name || material?.name || "", purchase_specification: current.purchase_specification || material?.specification || "", purchase_unit: current.purchase_unit || material?.purchase_unit || material?.unit || "" })); }} className="mt-1 h-10 w-full border border-[#C7C7CC] px-2 text-sm text-[#1C1C1E]"><option value="">请选择</option>{materials.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} · {item.specification}</option>)}</select></label><Text label="供应商货号" value={form.supplier_item_code} onChange={(value) => set("supplier_item_code", value)} /><Text label="供应商商品名称" value={form.supplier_item_name} onChange={(value) => set("supplier_item_name", value)} /><Text label="采购规格" value={form.purchase_specification} onChange={(value) => set("purchase_specification", value)} /><Text label="采购单位" value={form.purchase_unit} onChange={(value) => set("purchase_unit", value)} /><NumberField label="单位换算" value={form.conversion_rate} onChange={(value) => set("conversion_rate", value)} /><NumberField label="含税价" value={form.tax_inclusive_price} onChange={(value) => set("tax_inclusive_price", value)} /><NumberField label="税率（%）" value={form.tax_rate} onChange={(value) => set("tax_rate", value)} /><NumberField label="最小采购量" value={form.minimum_order_quantity} onChange={(value) => set("minimum_order_quantity", value)} /><NumberField label="交期（天）" value={form.lead_days} onChange={(value) => set("lead_days", value)} /><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={form.is_preferred} onChange={(event) => set("is_preferred", event.target.checked)} />设为该商品首选供应商</label><label className="text-xs text-[#636366] sm:col-span-2 lg:col-span-3">备注<textarea value={form.remark} onChange={(event) => set("remark", event.target.value)} className="mt-1 min-h-20 w-full border border-[#C7C7CC] p-3 text-sm text-[#1C1C1E]" /></label></div><Actions busy={busy} onClose={onClose} onSubmit={submit} /></Dialog>;
}

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="ui-dialog-backdrop" onMouseDown={onClose}><div className="ui-dialog ui-dialog--wide p-5" onMouseDown={(event) => event.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h3 className="ui-dialog__title">{title}</h3><button onClick={onClose} aria-label="关闭" className="ui-dialog__close">×</button></div>{children}</div></div>; }
function Actions({ busy, onClose, onSubmit }: { busy: boolean; onClose: () => void; onSubmit: () => Promise<void> }) { return <div className="mt-5 flex justify-end gap-2 border-t border-[#E7E7EB] pt-4"><button onClick={onClose} className="ui-button ui-button--secondary">取消</button><button disabled={busy} onClick={() => void onSubmit()} className="ui-button ui-button--primary">{busy ? "正在保存..." : "保存"}</button></div>; }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs text-[#636366]">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full border border-[#C7C7CC] px-3 text-sm text-[#1C1C1E]" /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-[#636366]">{label}<input type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value) || 0)} className="mt-1 h-10 w-full border border-[#C7C7CC] px-3 text-sm text-[#1C1C1E]" /></label>; }
function Empty({ text, tall }: { text: string; tall?: boolean }) { return <div className={`flex items-center justify-center text-sm text-[#8E8E93] ${tall ? "min-h-[560px]" : "py-12"}`}>{text}</div>; }
function apiMessage(error: unknown, fallback: string) { return (error as { userMessage?: string; message?: string })?.userMessage || (error as { message?: string })?.message || fallback; }
