"use client";

import { Calculator, CalendarDays, Download, RefreshCw, Save, WalletCards } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import NoticeDialog from "@/components/door-cad/NoticeDialog";
import WorkspaceHeader from "@/components/workspace/WorkspaceHeader";
import WorkspaceTabs from "@/components/workspace/WorkspaceTabs";
import { calculatePayroll, getAttendance, getEmployees, getPayrollPeriod, getPayrollPeriods, saveAttendance, updatePayrollEntry, updatePayrollStatus } from "@/lib/operationsApi";
import type { AttendanceRow, PayrollEntry, PayrollPeriod, WorkforceEmployee } from "@/lib/operationsTypes";

const monthNow=()=>new Date().toISOString().slice(0,7);
const nextStatus:Record<string,string>={"草稿":"待审核","待审核":"已审批","已审批":"已锁定","已锁定":"草稿"};
export default function PayrollPage(){
  const [tab,setTab]=useState<"payroll"|"attendance">("payroll"); const [month,setMonth]=useState(monthNow()); const [periods,setPeriods]=useState<PayrollPeriod[]>([]); const [period,setPeriod]=useState<PayrollPeriod|null>(null); const [employees,setEmployees]=useState<WorkforceEmployee[]>([]); const [attendance,setAttendance]=useState<AttendanceRow[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<{title:string;message:string}|null>(null); const [attendanceForm,setAttendanceForm]=useState({employee_id:0,work_date:new Date().toISOString().slice(0,10),regular_hours:8,overtime_hours:0,leave_hours:0,remark:""});
  const load=useCallback(async()=>{const [p,e,a]=await Promise.all([getPayrollPeriods(),getEmployees(),getAttendance(month)]);setPeriods(p);setEmployees(e.filter(x=>x.is_active));setAttendance(a);},[month]);
  useEffect(()=>{void load().catch(error=>setNotice({title:"加载失败",message:msg(error,"工资数据加载失败")}));},[load]);
  const total=useMemo(()=>period?.entries?.reduce((sum,row)=>sum+Number(row.payable_amount||0),0)||0,[period]);
  const calculate=async()=>{setBusy(true);try{const result=await calculatePayroll(month);setPeriod(result.period);setNotice({title:"计算完成",message:result.message});await load();}catch(error){setNotice({title:"计算失败",message:msg(error,"月度工资计算失败")});}finally{setBusy(false);}};
  const saveEntry=async(row:PayrollEntry)=>{setBusy(true);try{const result=await updatePayrollEntry(row.id,row);setPeriod(result.period);setNotice({title:"保存成功",message:result.message});}catch(error){setNotice({title:"保存失败",message:msg(error,"工资明细保存失败")});}finally{setBusy(false);}};
  const transit=async()=>{if(!period)return;setBusy(true);try{const result=await updatePayrollStatus(period.id,nextStatus[period.status] as PayrollPeriod["status"]);setPeriod(result.period);setNotice({title:"状态已更新",message:result.message});await load();}catch(error){setNotice({title:"操作失败",message:msg(error,"工资状态更新失败")});}finally{setBusy(false);}};
  const exportCsv=()=>{if(!period?.entries?.length)return;const header=["员工编号","姓名","班组","基本工资","计件","加班","补贴","奖金","扣款","社保","个税","其他代扣","应发","备注"];const rows=period.entries.map(r=>[r.employee_no,r.name,r.team,r.base_salary,r.piecework_amount,r.overtime_amount,r.allowance,r.bonus,r.deduction,r.social_insurance,r.tax,r.other_withholding,r.payable_amount,r.remark]);const csv="\ufeff"+[header,...rows].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`工资表_${month}.csv`;a.click();URL.revokeObjectURL(a.href);};
  return <div className="min-h-screen bg-[#F2F2F7]"><main className="workspace-page workspace-page--wide space-y-4"><WorkspaceHeader title="工资管理" description="考勤、生产计件与人工调整按月汇总；审批锁定后形成不可直接修改的工资凭据。" context={<><WalletCards size={14}/>经营管理 / 人员工资</>} actions={<button className="ui-button ui-button--secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/>刷新</button>}/><div className="flex flex-wrap items-center gap-3"><WorkspaceTabs items={[{key:"payroll",label:"月度工资"},{key:"attendance",label:"考勤登记"}] as const} value={tab} onChange={setTab} ariaLabel="工资管理视图"/><label className="ml-auto flex items-center gap-2 text-sm"><CalendarDays size={15}/><input type="month" value={month} onChange={e=>{setMonth(e.target.value);setPeriod(null);}} className="h-9 border border-[#C7C7CC] bg-white px-3"/></label></div>
  {tab==="attendance"?<AttendancePanel rows={attendance} employees={employees} form={attendanceForm} setForm={setAttendanceForm} busy={busy} submit={async()=>{if(!attendanceForm.employee_id)return setNotice({title:"无法保存",message:"请选择员工"});setBusy(true);try{const result=await saveAttendance(attendanceForm);setNotice({title:"保存成功",message:result.message});await load();}catch(error){setNotice({title:"保存失败",message:msg(error,"考勤保存失败")});}finally{setBusy(false);}}}/>:<section className="workspace-panel overflow-hidden"><header className="workspace-panel__header"><div><h2>{month} 工资表</h2><p>{period?`${period.status} · ${period.entries?.length||0} 人 · 合计 ¥${total.toFixed(2)}`:"选择已有期间或重新汇总当月数据"}</p></div><div className="flex flex-wrap gap-2"><select value={period?.id||""} onChange={e=>{const found=periods.find(p=>p.id===Number(e.target.value));if(found)void getPayrollPeriod(found.id).then(detail=>{setMonth(found.month);setPeriod(detail);});}} className="h-9 border border-[#C7C7CC] bg-white px-3 text-sm"><option value="">历史月份</option>{periods.map(p=><option key={p.id} value={p.id}>{p.month} · {p.status}</option>)}</select><button className="ui-button ui-button--primary" disabled={busy||period?.status==="已锁定"} onClick={()=>void calculate()}><Calculator size={15}/>汇总计算</button><button className="ui-button ui-button--secondary" disabled={!period} onClick={exportCsv}><Download size={15}/>导出 CSV</button>{period&&<button className="ui-button ui-button--secondary" disabled={busy} onClick={()=>void transit()}>{period.status==="已锁定"?"解锁为草稿":nextStatus[period.status]}</button>}</div></header><PayrollTable period={period} setPeriod={setPeriod} save={saveEntry} busy={busy}/></section>}
  </main>{notice&&<NoticeDialog title={notice.title} message={notice.message} onConfirm={()=>setNotice(null)}/>}</div>;
}

function PayrollTable({period,setPeriod,save,busy}:{period:PayrollPeriod|null;setPeriod:(p:PayrollPeriod)=>void;save:(r:PayrollEntry)=>Promise<void>;busy:boolean}){if(!period)return <div className="p-12 text-center text-sm text-[#8E8E93]">点击“汇总计算”生成本月工资表</div>;const locked=period.status==="已锁定";const change=(id:number,key:keyof PayrollEntry,value:string|number)=>setPeriod({...period,entries:period.entries?.map(r=>r.id===id?{...r,[key]:value}:r)});return <div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-sm"><thead><tr>{["员工","基本工资","计件工资","加班金额","补贴","奖金","扣款","社保","个税","其他代扣","应发工资","备注","操作"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{period.entries?.map(row=><tr key={row.id}><td><strong>{row.employee_no}</strong><small>{row.name} · {row.team||"未分组"}</small></td><Money value={row.base_salary} disabled/><Money value={row.piecework_amount} disabled/>{(["overtime_amount","allowance","bonus","deduction","social_insurance","tax","other_withholding"] as const).map(key=><Money key={key} value={row[key]} disabled={locked} onChange={v=>change(row.id,key,v)}/>) }<td className="font-semibold">¥{Number(row.payable_amount).toFixed(2)}</td><td><input disabled={locked} value={row.remark||""} onChange={e=>change(row.id,"remark",e.target.value)}/></td><td><button className="ui-button ui-button--secondary" disabled={busy||locked} onClick={()=>void save(row)}><Save size={14}/>保存</button></td></tr>)}</tbody></table><style jsx>{`th,td{border-bottom:1px solid #e5e5ea;padding:.65rem;text-align:left}th{background:#f7f7f9;color:#636366;font-size:.75rem;font-weight:500}td small{display:block;color:#636366;margin-top:.2rem}td input{height:2.25rem;width:120px;border:1px solid #c7c7cc;padding:0 .5rem}td input:disabled{border-color:transparent;background:transparent}`}</style></div>}
function Money({value,disabled,onChange}:{value:number;disabled?:boolean;onChange?:(v:number)=>void}){return <td><input type="number" disabled={disabled} value={value||""} onChange={e=>onChange?.(Number(e.target.value)||0)}/></td>}
function AttendancePanel({rows,employees,form,setForm,busy,submit}:{rows:AttendanceRow[];employees:WorkforceEmployee[];form:{employee_id:number;work_date:string;regular_hours:number;overtime_hours:number;leave_hours:number;remark:string};setForm:(v:typeof form)=>void;busy:boolean;submit:()=>Promise<void>}){return <section className="workspace-panel overflow-hidden"><header className="workspace-panel__header"><div><h2>每日考勤</h2><p>同一员工同一天重复登记会覆盖原记录。</p></div></header><div className="grid gap-3 border-b bg-[#FAFAFB] p-4 md:grid-cols-3 xl:grid-cols-6"><select value={form.employee_id||""} onChange={e=>setForm({...form,employee_id:Number(e.target.value)})}><option value="">选择员工</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_no} · {e.name}</option>)}</select><input type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})}/><input type="number" value={form.regular_hours} onChange={e=>setForm({...form,regular_hours:Number(e.target.value)||0})} placeholder="正常工时"/><input type="number" value={form.overtime_hours} onChange={e=>setForm({...form,overtime_hours:Number(e.target.value)||0})} placeholder="加班工时"/><input value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})} placeholder="备注"/><button className="ui-button ui-button--primary" disabled={busy} onClick={()=>void submit()}><Save size={15}/>保存考勤</button></div><div className="divide-y">{rows.length?rows.map(r=><div key={r.id} className="grid gap-2 p-3 text-sm md:grid-cols-6"><strong>{r.employee_no} · {r.name}</strong><span>{r.work_date}</span><span>正常 {r.regular_hours}h</span><span>加班 {r.overtime_hours}h</span><span>请假 {r.leave_hours}h</span><span>{r.remark||"-"}</span></div>):<div className="p-10 text-center text-sm text-[#8E8E93]">本月暂无考勤</div>}</div><style jsx>{`input,select{height:2.5rem;width:100%;border:1px solid #c7c7cc;background:#fff;padding:0 .75rem;font-size:.875rem}`}</style></section>}
function msg(error:unknown,fallback:string){return (error as {userMessage?:string;message?:string})?.userMessage||(error as {message?:string})?.message||fallback}
